# Generated by Django 4.2.7 on 2024-10-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='qualification',
            field=models.TextField(blank=True, null=True, verbose_name='Квалификация'),
        ),
    ]
