# Generated by Django 4.2.7 on 2024-10-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_event_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmember',
            options={'verbose_name': 'Участник события', 'verbose_name_plural': 'Участники событий'},
        ),
    ]
