# Generated by Django 4.2.7 on 2024-10-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        ('calendarapp', '0004_alter_eventmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sport.direction'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sport.trainer'),
        ),
    ]
