# Generated by Django 3.0.8 on 2021-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20210520_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('isComplete', models.BooleanField(default=False)),
            ],
        ),
    ]
