# Generated by Django 3.0.8 on 2021-05-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_auto_20210520_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
