# Generated by Django 3.0.8 on 2021-05-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='Room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Room'),
            preserve_default=False,
        ),
    ]
