# Generated by Django 3.0.8 on 2021-05-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0014_booking_request_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
