# Generated by Django 3.0.8 on 2021-05-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0015_room_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
    ]
