# Generated by Django 3.0.8 on 2021-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_remove_room_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facilty', models.CharField(max_length=200)),
            ],
        ),
    ]
