# Generated by Django 3.0.8 on 2021-05-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_room_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_Facility',
        ),
    ]
