# Generated by Django 3.0.8 on 2021-05-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0019_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Facility'),
            preserve_default=False,
        ),
    ]
