# Generated by Django 3.0.8 on 2021-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0020_room_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Facility',
        ),
        migrations.AddField(
            model_name='room',
            name='Facility',
            field=models.ManyToManyField(to='calendarapp.Facility'),
        ),
    ]
