# Generated by Django 3.0.8 on 2021-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0021_auto_20210524_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='Room',
        ),
        migrations.AddField(
            model_name='booking_request',
            name='number_of_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
