# Generated by Django 3.0.8 on 2021-05-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0022_auto_20210524_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='number_of_person',
        ),
        migrations.AddField(
            model_name='booking_request',
            name='Room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Room'),
            preserve_default=False,
        ),
    ]
