# Generated by Django 3.0.8 on 2021-05-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0023_auto_20210524_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='Room',
        ),
    ]
