# Generated by Django 3.0.8 on 2021-05-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0024_remove_booking_request_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='description',
        ),
    ]
