# Generated by Django 3.0.8 on 2021-05-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0026_auto_20210524_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Facility',
        ),
    ]
