# Generated by Django 3.0.8 on 2021-05-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0028_auto_20210525_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Facility',
        ),
    ]
