# Generated by Django 3.0.8 on 2021-06-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0030_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_request',
            name='Room',
        ),
        migrations.AddField(
            model_name='event',
            name='Room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Room'),
            preserve_default=False,
        ),
    ]
