# Generated by Django 3.0.8 on 2021-06-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0031_auto_20210602_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
