# Generated by Django 2.1.7 on 2021-06-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0032_auto_20210602_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_request',
            name='Room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Room'),
            preserve_default=False,
        ),
    ]
